version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4445:4444"

  node1:
    image: selenium/node-chrome-debug:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_SESSION=10 
      - NODE_MAX_INSTANCES=10
      - HUB_PORT=4444

  node2:
    image: selenium/node-chrome-debug:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_SESSION=10 
      - NODE_MAX_INSTANCES=10
      - HUB_PORT=4444
